services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  app:
    build:
      context: ./
    container_name: csrs-backend
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - REDIS_URL=redis://redis:6379
    working_dir: /app
    depends_on:
      - redis
    env_file:
      - .env
    expose:
      - 3000
