services:
  minio:
    image: "minio/minio:RELEASE.2024-02-17T01-15-57Z"
    container_name: minio
    restart: always
    command: server --console-address ":9090" /data
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: csrc_admin
      MINIO_ROOT_PASSWORD: csrc@123
    volumes:
      - ./minio-data:/data

  pdb:
    image: "postgres:15"
    container_name: pdb
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: csrcDB
    expose:
      - 5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    container_name: redis
    volumes:
      - ./redis-data:/data

  app:
    build:
      context: ./
    container_name: csrs-backend
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - REDIS_URL=redis://redis:6379
    working_dir: /app
    depends_on:
      - redis
      - pdb
      - minio

    env_file:
      - .env
    expose:
      - 3000
