services:
  minio:
    image: "minio/minio:RELEASE.2024-02-17T01-15-57Z"
    container_name: minio
    restart: always
    command: server --console-address ":9090" /data
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: csrc_admin
      MINIO_ROOT_PASSWORD: csrc@123
    volumes:
      - ./minio-data:/data

  pdb:
    image: "postgres:15"
    container_name: pdb
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: csrcDB
    expose:
      - 5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    container_name: redis
    volumes:
      - ./redis-data:/data

  mq:
    hostname: "mailmq"
    image: rabbitmq:management
    container_name: mail-rabbitmq
    volumes:
      - "db:/var/lib/rabbitmq/mnesia/"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 20s
      retries: 5

  pub:
    image: psgecampus/mail-publisher
    restart: on-failure
    environment:
      - PORT=8080
      - CLIENT_ID=675518225398-sdu9glg7i88e0r7tq4f4cdmvj9v7et99.apps.googleusercontent.com
      - CLIENT_SECRET=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
      - REFRESH_TOKEN=1//04Icjw1VE-6O9CgYIARAAGAQSNwF-L9Irlj12b__QjGGD_3eE2A0NrN4CubE84yxHKwin6P1AgnfAGMmM7rOE3X2e3Dy9AdJpNwg
      - FROM_EMAIL=ecampus@psgtech.ac.in
      - TZ=Asia/Kolkata
      - AMQP_HOST=amqp://mq
      - AMQP_QUEUE=mails
    ports:
      - "9999:8080"
    depends_on:
      mq:
        condition: service_healthy
    container_name: mail-publisher

  sub:
    image: psgecampus/mail-subscriber
    restart: on-failure
    environment:
      - PORT=8080
      - CLIENT_ID=675518225398-sdu9glg7i88e0r7tq4f4cdmvj9v7et99.apps.googleusercontent.com
      - CLIENT_SECRET=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
      - REFRESH_TOKEN=1//04Icjw1VE-6O9CgYIARAAGAQSNwF-L9Irlj12b__QjGGD_3eE2A0NrN4CubE84yxHKwin6P1AgnfAGMmM7rOE3X2e3Dy9AdJpNwg
      - FROM_EMAIL=ecampus@psgtech.ac.in
      - TZ=Asia/Kolkata
      - AMQP_HOST=amqp://mq
      - AMQP_QUEUE=mails
    depends_on:
      mq:
        condition: service_healthy
    container_name: mail-subscriber
  app:
    build:
      context: ./
    container_name: csrs-backend
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - REDIS_URL=redis://redis:6379
    working_dir: /app
    depends_on:
      - redis
      - pdb
      - minio

    env_file:
      - .env
    expose:
      - 3000
volumes:
  db:
    driver: local
